name: tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        python:
        # Build on pre-releases until stable, then stable releases.
        # actions/setup-python#213
        - ~3.7.0-0
        - ~3.10.0-0
        - ~3.11.0-0
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        include:
        - platform: ubuntu-latest
          python: 'pypy3.9'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run tests
        run: tox

  test_cygwin:
    # disabled due to lack of Rust support pypa/setuptools#3921
    if: ${{ false }}
    strategy:
      matrix:
        python:
        - 39
        platform:
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@v2
        with:
          platform: x86_64
          packages: >-
            python${{ matrix.python }},
            python${{ matrix.python }}-devel,
            python${{ matrix.python }}-pytest,
            python${{ matrix.python }}-tox,
            gcc-core,
            gcc-g++,
            ncompress
      - name: Run tests
        shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -leo pipefail -o igncr {0}
        run: tox

  ci_setuptools:
    # Integration testing with setuptools
    strategy:
      matrix:
        python:
        - "3.10"
        platform:
        - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    env:
      SETUPTOOLS_USE_DISTUTILS: local
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Check out pypa/setuptools
        uses: actions/checkout@v3
        with:
          repository: pypa/setuptools
          ref: main
          path: integration/setuptools
      - name: Replace vendored distutils
        run: |
          cd integration/setuptools/setuptools
          rm -rf _distutils
          cp -rp ../../../distutils _distutils
      - name: Run setuptools tests
        run: |
          cd integration/setuptools
          tox
        env:
          VIRTUALENV_NO_SETUPTOOLS: null

  release:
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Release
        run: tox -e release
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
